openapi: 3.0.3
info:
  title: Banco XYZ Microservicio Cliente - OpenAPI 3.0
  description: |-
    Documentación del API para administrar clientes del banco XYZ.
  contact:
    email: lramosol@emeal.nttdata.com
  version: 1.0.11
servers:
  - url: http://localhost:1010
tags:
  - name: cliente
    description: Información y administración de clientes
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /clientes:
    post:
      tags:
        - cliente
      summary: Nuevo cliente
      description: Crear un cliente nuevo.
      operationId: crearCliente
      requestBody:
        description: Información de un nuevo cliente.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
      security:
        - bancoxyz_auth: [write]
    get:
      tags:
        - cliente
      summary: Lista de clientes
      description: Listar todos los clientes.
      operationId: listarClientes
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'
        '404':
          description: Clients not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
      security:
        - bancoxyz_auth: [read]
  /clientes/{id}:
    get:
      tags:
        - cliente
      summary: Detalle de un cliente
      description: Obtener detalles de un cliente por su ID.
      operationId: getClientePorId
      parameters:
        - name: id
          in: path
          description: ID del cliente
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '400':
          description: Invalid ID value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '404':
          description: Client not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
      security:
        - bancoxyz_auth: [read]
    put:
      tags:
        - cliente
      summary: Actualizar cliente
      description: Actualizar los datos de un cliente.
      operationId: actualizarCliente
      parameters:
        - name: id
          in: path
          description: ID del cliente
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Información del cliente.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '400':
          description: Invalid ID value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '404':
          description: Client not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
      security:
        - bancoxyz_auth: [update]
    delete:
      tags:
        - cliente
      summary: Eliminar un cliente
      description: Eliminar un cliente.
      operationId: eliminarCliente
      parameters:
        - name: id
          in: path
          description: ID del cliente a eliminar
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Client deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '400':
          description: Invalid ID value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '409':
          description: Conflict - Client has active accounts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
      security:
        - bancoxyz_auth: [delete]
components:
  schemas:
    Cliente:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Identificador único
          example: 10
        nombre:
          type: string
          description: Obligatorio
        apellido:
          type: string
          description: Obligatorio
        dni:
          type: string
          description: Obligatorio, único para cada cliente
          example: '12345678'
        email:
          type: string
          format: email
          description: Validación de formato de correo
      xml:
        name: cliente
    ResponseModel:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 404
        type:
          type: string
          example: 'success'
        message:
          type: string
          description: A human-readable message
        data:
          $ref: '#/components/schemas/Cliente'
      xml:
        name: '##default'
  requestBodies:
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Cliente'
  securitySchemes:
    bancoxyz_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://bancoxyz.swagger.io/oauth/authorize
          scopes:
            write: Grants permission to create new clients.
            read: Grants read access to clients information.
            update: Grants permission to update clients information.
            delete: Grants permission to delete clients.